### ISSUE TITLE
6D pose

### ISSUE THREAD

**Issue by wlpabc123** [XingqunQi-lab/EmotionGestures#3]
This is really great work! 
You mentioned in the paper that you are using 6D skeleton data, and the skeleton data in the currently published dataset is also 6D. How can the 6D skeleton data be converted to its original 3D form? Can you provide this part of the tool or code?

**Comment by XingqunQi-lab** [comment]
Hi,
Thank you very much for your questions. For the conversion between the 3D and 6D rotation representation please refer to 'https://arxiv.org/abs/1812.07035'
